Repository eclipse/kiso, pull requests merged in 2020-03, with the labels that each got.

#147 Rewrite changelog in human readable form (#2)
  CHANGELOG.md
Labels: Epic: Documentation

#151 Feature/#146 integrate stm32f7 library into build system
  config/thirdparty/stm32cubef7/stm32f7xx_hal_conf.h
  thirdparty/stm32cubef7/CMakeLists.txt
Labels: Epic: MPS, Epic: RefHW ST NUCLEO-F767ZI

#152 Feature/#48 change survey to lime
  docs/website/content/Questionnaires/_index.md
Labels: Epic: Documentation

#157 Feature/#156 route testinterface uart to usb
  boards/NucleoF767/bsp/source/bsp_api_testif.c
Labels: Epic: RefHW ST NUCLEO-F767ZI, Type: Feature

#158 Feature/add readme to nucleo f767 c-leds example
  examples/NucleoF767/c-leds/readme.md
Labels: Epic: Documentation, Epic: RefHW ST NUCLEO-F767ZI, Prio: High

#180 Fix default build failing when no debugger is installed
  cmake/FlashTarget.cmake
Labels: Type: Bug

#171 Kiso intro + infographic
  README.md
  docs/website/content/images/Kiso_infographic.png
Labels: Epic: Documentation, Type: Feature
